repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (poetry, autofix)
        entry: poetry run ruff check
        language: system
        types: [python]
        args: ["--fix", "--unsafe-fixes", "."]
        pass_filenames: false

      - id: black
        name: black (poetry)
        entry: poetry run black
        language: system
        types: [python]
        args: ["--config=pyproject.toml", "."]
        pass_filenames: false

      - id: pytest
        name: pytest (Airflow DAG validation)
        entry: poetry run pytest
        language: system
        types: [python]
        args: ["-q", "tests/test_dags_import.py"]
        pass_filenames: false

      - id: check-dag-id
        name: "(Custom) dag_id existence"
        entry: poetry run python .hooks/check_dag_id_existence.py
        language: system
        types: [python]
        files: ^dags/.*\.py$
        pass_filenames: true


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      #- id: check-json
        exclude: ^\.vscode/
